## 1. Write a NumPy program to test whether none of the elements of a given array is zero.


In [5]:
import numpy as np

In [7]:
element1 = np.array([1, 2, 3, 4])
print(f"check of zero =  {np.all(element1)}")
element2 = np.array([0, 5, 7, 9])
print(f"check of zero =  {np.all(element2)}")


check of zero =  True
check of zero =  False


2. Write a NumPy program to test whether any of the elements of a given array is non-zero.


In [21]:
x = np.array([1, 0, 0, 0])
print(x)
print(f" check of non zero array : {np.any(x)}")
y = np.array([0, 0, 0, 0])
print(y)
print(f" check of non zero array : {np.any(y)}")


[1 0 0 0]
 check of non zero array : True
[0 0 0 0]
 check of non zero array : False


3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [28]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
fives_array = 5 * np.ones(10)
print(f"Array of 10 zeros & 10 ones & 10 fives: {zeros_array} , {ones_array} , {fives_array} ")


Array of 10 zeros & 10 ones & 10 fives: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] , [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] , [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 


5. Write a NumPy program to create an array of the integers from 30 to70.

In [40]:
array = np.arange(30, 71)
print(f"Array of the integers from 30 to 70 = \n {array}")

Array of the integers from 30 to 70 = 
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


6. Write a NumPy program to create a 3x3 identity matrix


In [48]:
identity_matrix = np.eye(3,3)
print(f" identity matrix for 3x3 = \n {identity_matrix}")

 identity matrix for 3x3 = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1


In [64]:
random_number = np.random.random()
print(f"random number between 0 and 1 = {random_number}")

random number between 0 and 1 = 0.5781555129442957


8. Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [70]:
standard_normal_distribution = np.random.randn(15)
print(standard_normal_distribution)

[ 1.41240784 -1.20389591  0.0253038   1.35226299 -0.97985724  1.02890097
  1.14454077  1.06816151  1.2391147  -0.42654204 -1.04621714  0.18613943
  0.90127003 -0.8974938   0.00549104]


9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.


In [76]:
vector = np.arange(15, 56)
print(f"original value of vector = \n {vector}")
vector = vector[1:-1]
print(f"new value of vector = \n {vector}")

original value of vector = 
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
new value of vector = 
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [79]:
arbitrary_integers = np.random.randint(0, 11, 5)
print(f"arbitrary integers from 0 to 10 = \n {arbitrary_integers}")

arbitrary integers from 0 to 10 = 
 [9 6 7 4 1]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.

In [85]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [88]:
diagonal_matrix = np.diag([1, 2, 3, 4, 5])
print(diagonal_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.

In [89]:
matrix = np.zeros((4, 4))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1
print(matrix)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.

---



In [100]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
compressed_array = np.savez('compressed_array.npz', array1, array2)
y = np.load('compressed_array.npz')
print(y)

NpzFile 'compressed_array.npz' with keys: arr_0, arr_1


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
Select

In [110]:
random_values = np.random.rand(40)
print(f"Randomly generated values= \n {random_values}")

Randomly generated values= 
 [0.88330609 0.62367221 0.75094243 0.34889834 0.26992789 0.89588622
 0.42809119 0.96484005 0.6634415  0.62169572 0.11474597 0.94948926
 0.44991213 0.57838961 0.4081368  0.23702698 0.90337952 0.57367949
 0.00287033 0.61714491 0.3266449  0.5270581  0.8859421  0.35726976
 0.90853515 0.62336012 0.01582124 0.92943723 0.69089692 0.99732285
 0.17234051 0.13713575 0.93259546 0.69681816 0.06600017 0.75546305
 0.75387619 0.92302454 0.71152476 0.12427096]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number

In [123]:
value = int(input("Enter a value: "))
x = np.array([[1,3,5,7,9] , [2,4,6,8,10]])
y = np.extract(x > value, x)
print(f"Numbers greater than {value} = \n {y}")

Enter a value: 5
Numbers greater than 5 = 
 [ 7  9  6  8 10]
